apiVersion: batch/v1
kind: Job
metadata:
  name: "create-db-schema"
  namespace: "${project_namespace}"
spec:
  template:
    spec:
      containers:
      - name: "create-db-schema-container"
        image: "${container_image}"
        command: ["python3",  "/test-artifacts/scripts/create-data-model.py"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: db_host
              name: db-params
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: db_port
              name: db-params
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-credentials
        - name: DB_CONNECT_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: db_connect_timeout
              name: db-params
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              key: db_schema
              name: db-params
        volumeMounts:
        - name: scripts
          mountPath: "/test-artifacts/scripts"
      restartPolicy: OnFailure
      volumes:
      - name: scripts
        configMap:
          name: python-scripts
          defaultMode: 0500
          items:
          - key: create-data-model.py
            path: create-data-model.py
  backoffLimit: 3